/* Sprite-sheet fighters (CraftPix cats, zombies & chibi heroes).
   Sheets + metadata are generated by tools/build_sprites.py into sprites/ and js/sprites-meta.js.
   Pose is controlled by a CSS class (pose-idle / pose-run / pose-eat / pose-cheer / pose-charred)
   on the WRAPPER element; each pose shows one .anim strip. */
(function () {
  'use strict';
  const META = window.SPRITES, ORDER = window.SPRITES_ORDER;
  const CHARACTERS = ORDER.map(id => Object.assign({ id }, META[id]));

  function animDiv(key, a, once) {
    const dur = (a.frames / a.fps).toFixed(3);
    const anim = once
      ? `stripOnce ${dur}s steps(${a.frames - 1}) 1 forwards`
      : `stripLoop ${dur}s steps(${a.frames}) infinite`;
    const endPct = (-(100 * (a.frames - 1)) / a.frames).toFixed(3);
    return `<div class="anim ${key}" style="aspect-ratio:${a.ar};height:${((a.hr || 1) * 100).toFixed(1)}%">` +
      `<img class="strip" src="${a.file}" alt="" draggable="false" ` +
      `style="width:${a.frames * 100}%;--end:${endPct}%;animation:${anim}"></div>`;
  }

  /**
   * Render a fighter. opts.full=false renders only the idle strip (roster cards),
   * full render includes move/eat/dead strips for the race screen and results.
   */
  function renderCharacter(c, opts = {}) {
    const an = c.anims;
    const full = opts.full !== false;
    const hasMove = full && an.move, hasDead = full && an.dead;
    let html = `<div class="sprite-box${hasMove ? '' : ' hop'}${hasDead ? '' : ' no-dead'}" style="aspect-ratio:${an.idle.ar}">`;
    html += animDiv('idle', an.idle, false);
    if (hasMove) html += animDiv('move', an.move, false);
    if (full && an.eat) html += animDiv('eat', an.eat, true);
    if (full && an.hurt) html += animDiv('hurt', an.hurt, true);
    if (hasDead) html += animDiv('dead', an.dead, true);
    html += '</div>';
    return html;
  }

  function shade(hex, f) {
    const n = parseInt(hex.slice(1), 16);
    const ch = (x) => Math.round(x * f);
    return `rgb(${ch((n >> 16) & 255)},${ch((n >> 8) & 255)},${ch(n & 255)})`;
  }

  /* Card background: diagonal energy burst in the fighter's accent color. */
  function cardBg(c) {
    return `background:
      radial-gradient(circle at 50% 105%, rgba(255,255,255,.35), transparent 55%),
      repeating-conic-gradient(from -15deg at 50% 60%, ${c.accent} 0deg 14deg, ${shade(c.accent, 0.55)} 14deg 28deg);`;
  }

  /* Warm the browser cache for a fighter's race sheets (call on lock-in). */
  const preloaded = new Set();
  function preload(c) {
    Object.values(c.anims).forEach(a => {
      if (preloaded.has(a.file)) return;
      preloaded.add(a.file);
      const img = new Image();
      img.src = a.file;
    });
  }

  window.Characters = { CHARACTERS, renderCharacter, cardBg, preload };
})();
